id: 'ask tj ???'
name: Application Not Using Client Credentials
description: |
  'This application is not using a client certificate or secret is not secure. 
   It is recommended that you review your needs and use an Authentication method for sign-in.'
requiredDataConnectors:
  - connectorId: '???'
    dataTypes:
      - Senserva Control
tactics:
  - Impact
query: |
  let timeframe = 60d;
  DashboardTest_CL
  | where TimeGenerated >= ago(timeframe)
  | where ControlName_s == 'ApplicationNotUsingClientCredentials'