id: 1BDB9A37-DC72-4C5A-A222-08443865DC0D
name: Application Not Using Client Credentials
description: |
  'This application is not using a client certificate or secret is not secure. 
   It is recommended that you review your needs and use an Authentication method for sign-in.'
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - Senserva Control
tactics:
  - Impact
query: |
  let timeframe = 60d;
  SenservaPro_CL
  | where TimeGenerated >= ago(timeframe)
  | where ControlName_s == 'ApplicationNotUsingClientCredentials'