id: 975419eb-7041-419c-b8f0-c4bf513cf2b2
name: Cisco Umbrella - High values of Uploaded Data
description: |
  'A normal user activity consists mostly of downloading data. Uploaded data is usually small unless there is a file/data upload to a website. Calculate the sum of BytesOut per Source-Destination pair over 12/24 hours.'
tactics:
  - Exfiltration
query: |
  let timeframe = 1d;
  Cisco_Umbrella 
  | where EventType == "proxylogs"
  | where TimeGenerated > ago(timeframe)
  | summarize sum(DstBytes) by SrcIpAddr,DstIpAddr
  | sort by sum_DstBytes desc
  | project SrcIpAddr, DstIpAddr
  | extend IpCustomEntity = SrcIpAddr