# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "Azure Sentinel Validations"

trigger:
  - master

jobs:
- template: .azure-pipelines/detectionsValidations.yaml
- template: .azure-pipelines/detectionTemplateSchemaValidation.yaml
- template: .azure-pipelines/kqlValidations.yaml
- template: .azure-pipelines/NonAsciiValidations.yaml
- template: .azure-pipelines/workbooksValidations.yaml
- template: .azure-pipelines/workbooksTemplateValidations.yaml
- template: .azure-pipelines/yamlFileValidator.yaml
- template: .azure-pipelines/jsonFileValidator.yaml
- template: .azure-pipelines/documentsLinkValidator.yaml
- template: .azure-pipelines/logoValidator.yaml
- template: .azure-pipelines/dataConnectorValidations.yaml