id: 155243f4-d962-4717-8a7b-b15b6d112660
name: McAfee ePO - Deployment failed
description: |
  'Detects when error sending alert occurs.'
severity: High
requiredDataConnectors:
  - connectorId: McAfeeePO
    dataTypes:
      - Syslog
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - DefenseEvasion
query: |
  let lbtime = 1h;
  McAfeeEPOEvent
  | where TimeGenerated > ago(lbtime)
  | where EventId in ('2412')
  | extend IPCustomEntity = DvcIpAddr, HostCustomEntity = DvcHostname
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
  - entityType: Host
    fieldMappings:
      - identifier: FullName
        columnName: HostCustomEntity
