id: b185ac23-dc27-4573-8192-1134c7a95f4f
name: Dynamics Encryption Settings Changed
description: |
  'This query looks for changes to the Data Encryption settings for Dynamics 365.
  Reference: https://docs.microsoft.com/microsoft-365/compliance/office-365-encryption-in-microsoft-dynamics-365'
severity: Medium
requiredDataConnectors:
  - connectorId: Dynamics365
    dataTypes:
      - Dynamics365Activity
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - DefenseEvasion
relevantTechniques:
  - T1600
query: |
  Dynamics365Activity
  | extend Message = tostring(split(OriginalObjectId, ' ')[0])
  | where Message =~ 'IsDataEncryptionActive'
  | project-reorder TimeGenerated, Message, UserId, ClientIP, InstanceUrl, UserAgent
  | extend timestamp = TimeGenerated, AccountCustomEntity = UserId, IPCustomEntity = ClientIP
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: AccountCustomEntity
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
