id: 56910d7b-aae7-452c-a3ed-89f72ef59234
name: SenservaPro AD Application Not Using Client Credentials
description: |
    'Searches for logs of AD Applications without Client Credentials (Key or Secret)'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Impact
relevantTechniques:
  - T1529
  - T1485
query: |
  SenservaPro_CL
  | where TimeGenerated >= ago(6h)
  | where ControlName_s == 'ApplicationNotUsingClientCredentials'