id: xxxxxxxxxxxxxxx
name: SlackAudit - Applications installed 
description: |
  'Applications installed.'
query: |
let lbtime = 24h;
SlackAudit
| where TimeGenerated > ago(lbtime)
| where DvcAction =~ 'app_installed'
| summarize by SrcUserName, EntityAppName