id: 9a2778a1-ac23-40f2-9579-a0c344127c89
name: SlackAudit - Applications installed 
description: |
  'This query detects application installation fact.'
tactics: Execution
query: |
  SlackAudit
  | where TimeGenerated > ago(lbtime)
  | where DvcAction =~ 'app_installed'
  | summarize by SrcUserName, EntityAppName