jobs:
- job: "DetectionsValidations"
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '3.1.300'
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/*.Tests.csproj'