jobs:
- job: "JsonFileValidation"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run tsc && node .script/jsonFileValidator.js'
    displayName: 'Json File Syntax Validation'