# This is a basic workflow to help you get started with Actions

name: Call Azure Pipeline

# Controls when the action will run. 
on:
  push:
    branches: [feature/* ]
  pull_request:
    branches: [ master, feature/* ]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/azure/Azure-Sentinel
            azure-pipeline-name: 'azure-pipelines.yml'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
