name: Excecute validations on private branches

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [feature/* ]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/azure/Azure-Sentinel
            azure-pipeline-name: 'Azure.Azure-Sentinel'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
